version: '3'

services:
  django_api_db:
    image: postgres
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
    ports:
      - "5432:5432"
  django_api:
    build:
      dockerfile: ./django.dockerfile
      context: .
    depends_on:
      - django_api_db
    environment:
      - DATABASE_NAME=django
      - DATABASE_PASSWORD=django
      - DATABASE_USER=django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    ## persist the container so we can 
    ## manually restart the server
    command: tail -f /dev/null   
    
