# Generated by Django 2.2.2 on 2019-06-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100)),
                ('content_body', models.CharField(max_length=5000)),
                ('css_tag', models.CharField(max_length=200)),
            ],
        ),
    ]
